paths:
  output_dir: '/output/'


ocr_device: 'gpu'
# device: 'cpu'
device: 'cuda:0'


pdf_processing:
  dpi: 300


table_detector:
  weights_path: '/models/doclayout_yolo_ft.pt'
  imgsz: 1024
  confidence_threshold: 0.4


ocr_extractor:
  lang: 'ch'
  use_angle_cls: True
  batch_size: 4

tablip:
  pretrained: './model/tablip.pth'
  vit: 'unitable-large'
  vit_ckpt_path: './models/unitable_weights/ssp_2m_large.pt'
  bert_ckpt_path: './models/bert-base-uncased'

  vit_grad_ckpt: False
  vit_ckpt_layer: 0

  batch_size: 1
  max_length: 384
  bbox_token_cnt: 384
  image_size: 448
  use_OTSL: true
  use_RoiAlign: true

  num_beams: 1


match_cols:
  map_database: './PDF_Table_Parse/data/map_database.json'
  excel_path: './PDF_Table_Parse/excel_data/同位素相关数据表.xlsx'
  heuristic:
    weight:
      lev: 0.3
      jac: 0.3 
      cos: 0.4
    similarity_threshold: 0.7
  llm:
    max_retry: 3
    llm_model: 'glm-4-plus'