train_file: './dataset/PubTabNet'
laion_path: ''

vit: 'unitable-large'
vit_ckpt_path: './weights/UniTable/ssp_2m_large.pt'
vit_grad_ckpt: False
vit_ckpt_layer: 0
bert_ckpt_path: './weights/bert-base-uncased'

image_size: 448
max_length: 320
batch_size: 8

queue_size: 16384
alpha: 0.4

# optimizer
weight_decay: 0.05
init_lr: 1e-8
min_lr: 5e-7
warmup_lr: 1e-8
lr_decay_rate: 0.9
max_epoch: 20
warmup_steps: 3000